---
title: "Keep Learning"
author: "Aaron Toth"
date: "2024-03-12"
output:
  html_document:
    toc: true
    theme: readable
---


**a. Cite 2 or 3 specific examples in the graphics in your portfolio where you used a feature of Altair that we did not learn in class. This might be using a new kind of mark or transform, or a way to customize a feature of the graphic, or a way to use interaction, or...**

  1. The first thing I learned was how to use `.mark_rule()` to add custom lines to plots. These can be used to emphasize sections of the graphic such as an axis, expectation, or logical boundary.
  
  2. I also learned a lot about how to deal with the quirkiness of `transform_lookup(`. Sometimes, in order to pass through more data and have it not match to only one observation, you have to give the function wide formatted data. 
  
  3. Furthermore, I got to play with the `mark_text()` for the first time. I did some simple but highly customized labels.



**b. You will also want to keep learning about principles of good graphics design. Cite 2 or 3 specific examples where you followed the advice in one of these resources. For the Knaflic book, provide specific page numbers. For the Wilke book provide at least section numbers. (Note: each section in that book has a URL which you could include as a link.)**
  
  1. I had some timeseries data from my mango dataset. As [Wilke](https://clauswilke.com/dataviz/visualizing-trends.html#showing-trends-with-a-defined-functional-form) writes:

> "When making scatter plots or time series , we are often more interested in the overarching trend of the data than in the specific detail of where each individual data point lies" (Chapter 14).

This led me to connect my timeseries and scatterplot data, rather than just presenting the points. However, I was still dissatisfied. I wanted stacked bars to show the overall trend and a connected scatterplot to show progression. 

I settled on an `vl_mark_area` chart, which follows Wilke's advice about continuity through timeseries and also gives me the stacking that I wanted.  

  2. When working on the New Challenge, I closely followed the design process and example of [Knaflic](https://github.com/Saurav6789/Books-/blob/master/Storytelling%20with%20Data%20Let%E2%80%99s%20Practice%20by%20Cole%20Nussbaumer%20Knaflic%20(z-lib.org).pdf). I drew multiple stretches and tried to decide which was best before I even started coding. Eventually, I settled on one similar to the one Knaflic makes on page 72. One thing I appreciate about his analysis of his version of the graphic is that he says: 

> "I chose to label the lines (and also added data labels) at the ends of the lines, eliminating any confusion over which series is which and reducing the work of going back and forth between a legend and the data" (Page 72).

Sometimes a simple graphic with good labels does the trick. 